### ISSUE TITLE
In itcoin_feature_solution_independent_blockchain_* could we use assert_equal() instead of assert()?

### ISSUE THREAD

**Issue by muxator** [bancaditalia/itcoin-core#11]
A recent CI run ([link](https://github.com/bancaditalia/itcoin-core/pull/10#issuecomment-1598854741)) failed.

The error log is not very useful because `itcoin_feature_solution_independent_blockchain_3_of_4.py` (ant its sibling `1_of_2`) use simple `assert()`, which do not print any diagnostic message on failure:

https://github.com/bancaditalia/itcoin-core/blob/d013b54238db5eba03b95be0216efa2673c8f5b6/test/functional/itcoin_feature_solution_independent_blockchain_3_of_4.py#L113

We could rework those tests in order to use `assert_equal()`, which on failure would print a comparison of the expected and the actual values.

**Comment by giuseppegalano-bi** [comment]
Done in 13eddb7706447b3b48d8c33066c6d90b8bbd3826
